#log config here
encoding="json"
info_filename="./log/server.log"
error_filename="./log/server_err.log"
max_size=1024
max_backups=30
max_age=7
compress=true
division="time"
level_separate=true
time_unit = "day"